package com.example.silkpay.model.enums;

public enum ErrorCode {
    SYSTEM_ERROR,
    AUTH_ERROR,
    ACCESS_DENIED,
    UNIQUE_RESOURCE_CONFLICT,
    RESOURCE_NOT_FOUND,
    INVALID_ARGUMENT,
    INVALID_TOKEN,
    EXPIRED_TOKEN,
    FILE_NOT_FOUND,
    TOO_LARGE_FILE_SIZE,
    REQUIRED_PARAMS_NOT_FOUND,
    ALREADY_EXISTS,
    ALREADY_REQUESTED,
    NOT_ALLOWED,
    NOT_FOUND,
    PASSWORDS_MISMATCH
}
